# Generated by Django 4.2.4 on 2023-08-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField()),
                ('hair_color', models.CharField(max_length=20)),
                ('eyes_color', models.CharField(max_length=20)),
                ('weight', models.PositiveSmallIntegerField()),
                ('character', models.CharField(max_length=20)),
                ('teeth', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('diseases', models.CharField(max_length=100)),
                ('disabilities', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=20)),
                ('cellphonenumber', models.PositiveSmallIntegerField()),
                ('user_name', models.CharField(max_length=16)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='userdatacomplete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=20)),
                ('numberphone', models.PositiveSmallIntegerField()),
                ('email', models.CharField(max_length=20)),
                ('age', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
